export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const INCREMENT_PAGINATION = 'INCREMENT_PAGINATION';
export const DECREMENT_PAGINATION = 'DECREMENT_PAGINATION';
